repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-docstring-first
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-merge-conflict
      - id: check-toml
      - id: check-yaml
      - id: fix-encoding-pragma
      - id: requirements-txt-fixer

  - repo: https://github.com/charliermarsh/ruff-pre-commit
    rev: v0.1.11
    hooks:
      - id: ruff
        args: [bb, --fix, --exit-non-zero-on-fix]
      - id: ruff-format
        args: [bb]
