[tool.poetry]
name = "bb"
version = "0.4.9"
description = "cli to manage bitbucket pull requests"
authors = ["psadi <adithya3494@gmail.com>"]
license = "MIT"
readme = "README.md"
packages = [
    { include = "bb" }
]

[tool.poetry.scripts]
bb = "bb:_bb"

[tool.poetry.dependencies]
python = ">=3.7.2,<4.0.0"
typer = {extras = ["all"], version = "^0.4.0"}
requests = ">=2.27.1"
rich = ">=11.1.0"
pyperclip = ">=1.8.2"
xdg = "^5.1.1"

[tool.poetry.group.dev.dependencies]
pytest = "^7.2.0"
tox = "^3.27.1"
pytest-cov = "^4.0.0"
pylint = "^2.15.6"
toml = "^0.10.2"

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["."]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
