name: Continuous Integration

on:
  workflow_dispatch: {}
  push:
    branches: [ "main" ]
  pull_request:
      types: [opened, synchronize, reopened]
      branches: [ "main" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.11"]
        os: [ubuntu-latest]
        language: [ 'python' ]
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare Environment, Sync Dependences and Run Tox
        run: |
          mkdir -p ~/.config/bb
          cp config.ini ~/.config/bb
          pdm sync
          pdm run tox

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args:
            -Dsonar.projectKey=psadi_bbcli
            -Dsonar.organization=psadi
            -Dsonar.python.version=3
            -Dsonar.sources=bb
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=tests

      - name: Initialize CodeQL
        uses: github/codeql-action/init@v2
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        uses: github/codeql-action/autobuild@v2

      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v2
        with:
          category: "/language:${{matrix.language}}"
