name: Continuous Integration

on:
  workflow_dispatch: {}
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize, reopened]
    branches: ["main"]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    permissions:
      actions: read
      contents: read
      security-events: write
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.12"]
        os: ["ubuntu-latest", "windows-latest", "macos-latest"]
        language: ["python"]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up PDM
        uses: pdm-project/setup-pdm@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Prepare Environment, Sync Dependences and Run Tox
        run: |
          mkdir -p ~/.config/bb
          cp config.ini ~/.config/bb
          pdm fix
          pdm sync
          pdm run tox

      - name: SonarCloud Scan
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: |
            -Dsonar.projectKey=psadi_bbcli
            -Dsonar.organization=psadi
            -Dsonar.python.version=3
            -Dsonar.sources=bb
            -Dsonar.tests=tests
            -Dsonar.python.coverage.reportPaths=coverage.xml
            -Dsonar.exclusions=tests

      - name: Initialize CodeQL
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}

      - name: Autobuild
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: github/codeql-action/autobuild@v3

      - name: Perform CodeQL Analysis
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: github/codeql-action/analyze@v3
        with:
          category: "/language:${{matrix.language}}"
          paths-ignore: |
            __pypackages__
            __pycache__
            .tox
            .pdm-build
            .ruff_cache
            build
            dist
            .vscode
            .github
