name: Update dependencies

on:
  schedule:
    - cron: 0 0 * * 0

jobs:
  update-dependencies:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update dependencies
        uses: pdm-project/update-deps-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: "chore: Update pdm.lock"
          pr-title: "auto: Update dependencies"
          update-strategy: reuse
          save-strategy: minimum
          unconstrained: false
          install-plugins: "true"
          sign-off-commit: "false"
